[book]
authors  = ["Zhaofeng Li"]
language = "en"
src      = "src"
title    = "Colmena @apiVersion@"

[output.html]
site-url           = "/@apiVersion@/"
git-repository-url = "https://github.com/nix-community/colmena"
edit-url-template  = "https://github.com/nix-community/colmena/edit/main/manual/{path}"

[output.linkcheck2]
follow-web-links = false

[preprocessor.colmena]
command  = "python3 preprocess.py"
renderer = ["html", "epub"]
